# Generated by Django 2.2.14 on 2020-08-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='private_notices.PrivateNotice', verbose_name='PrivateNotice Id'),
        ),
        migrations.AlterField(
            model_name='privatenotice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='PrivateNotice Date'),
        ),
        migrations.AlterField(
            model_name='privatenotice',
            name='pnotice',
            field=models.CharField(help_text='Please restrict the PrivateNotice length to 500.', max_length=500),
        ),
        migrations.AlterField(
            model_name='privatenotice',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatenotice',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
